apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: toleration-pod
  name: toleration-pod
spec:
  containers:
  - name: toleration-pod
    image: nginx
    resources: {}
  tolerations:
  - key: run
    operator: Equal
    value: mypod
    effect: NoSchedule
